name: Bug Report
description: Signaler un bug ou un problème
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce rapport de bug !

  - type: textarea
    id: description
    attributes:
      label: Description du problème
      description: Décrivez clairement le bug rencontré
      placeholder: "Décrivez le problème..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Listez les étapes pour reproduire le problème
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Décrivez ce qui devrait se passer
      placeholder: "Ce qui devrait se passer..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Décrivez ce qui se passe réellement
      placeholder: "Ce qui se passe réellement..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [ex. macOS 13.0]
        - Navigateur: [ex. Chrome 105]
        - Version du projet: [ex. 1.2.3]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informations supplémentaires
      description: Ajoutez toute autre information utile (captures d'écran, logs, etc.)
      placeholder: "Informations supplémentaires..."

  - type: checkboxes
    id: terms
    attributes:
      label: Vérifications
      options:
        - label: J'ai vérifié qu'il n'y a pas déjà un issue similaire
          required: true
        - label: J'ai testé avec la dernière version
          required: true